# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('slug', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nom')),
                ('initiative', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('initiative', 'slug'),
            },
        ),
    ]
